### PR TITLE
Skip metrics with invalid utf8, simpler edition

### PR DESCRIPTION
**Pull request by fungusakafungus**
Reverts Jimdo/statsd_exporter#2

### CODE REVIEW

**Comment by PirminTapken** [comment]
What about this @fungusakafungus

**Comment by fungusakafungus** [comment]
This reverts stuff in our master... I've merged something I shouldn't. Let's discuss in person.

**Comment by fungusakafungus** [comment]
I'll reset our master to upstream.

**Comment by fungusakafungus** [comment]
done

**Pull request closed without merging**
